[286] Add zendesk integration
DFE-Digital/get-help-with-tech pull request #1025
Opened 2021-01-04 15:52 UTC by aliuk2012

### Context

### Changes proposed in this pull request

### Guidance to review

2021-01-05 11:55 UTC, aliuk2012 commented on spec/services/zendesk_service_spec.rb
> +  xdescribe '#send!' do
Could really do with some help with these tests

2021-01-06 09:48 UTC, aldavidson requested changes
Just a few typos and a minor suggestion about moving the hard-coded IDs to a constant, otherwise all good :+1:

2021-01-06 09:48 UTC, aldavidson commented on app/form_objects/support_ticket/check_your_request_form.rb
> +    if Settings.zendesk.present? && Settings.zendesk.username.present? && Settings.zendesk.token.present?
```suggestion
    if Settings.zendesk&.username.present? && Settings.zendesk&.token.present?
```

2021-01-06 09:48 UTC, aldavidson commented on app/form_objects/support_ticket/check_your_request_form.rb
> +    if Settings.zendesk.present? && Settings.zendesk.username.present? && Settings.zendesk.token.present?
Just a bit more concise

2021-01-06 09:48 UTC, aldavidson commented on app/services/zendesk_service.rb
> +      ZendeskService.new(ticket).send!
```suggestion
      new(ticket).send!
```
It's already in the ZendeckService class scope, so you don't need to re-reference it

2021-01-06 09:48 UTC, aldavidson commented on app/services/zendesk_service.rb
> +        { id: '360011762698', value: ticket['telephone_number'] },
I guess these IDs have been created in the Zendesk user interface? I'm a little uncomfortable having them hard-coded within the method body here, could you maybe pull them out into a constant at the top? Something like:

```
class ZendeskService
  attr_accessor :ticket

  CUSTOM_FIELD_IDS = {
    contact_form: '360011490478',
    user_type: '360011798678',
    support_topics: '360011519218',
    telephone_number: '360011762698',
  }.freeze

(...)

  def send!
    ZendeskAPI::Request.create!(
      (...)
      custom_fields: [
        { id: CUSTOM_FIELD_IDS[:contact_form], value: 'contact_form' },
        { id: CUSTOM_FIELD_IDS[:user_type], value: ticket['user_type'] },
        { id: CUSTOM_FIELD_IDS[:support_topics], value: ticket['support_topics'] },
        { id: CUSTOM_FIELD_IDS[:telephone_number], value: ticket['telephone_number'] },
    ],
```

2021-01-06 09:48 UTC, aldavidson commented on spec/form_objects/support_ticket/check_your_request_form_spec.rb
> +  describe 'when not in production and znedesk creditials are not provided' do
```suggestion
  describe 'when zendesk credentials are not provided' do
```
Typo, and removed 'in production' as there's no mention of production in the test code

2021-01-06 09:48 UTC, aldavidson commented on spec/form_objects/support_ticket/check_your_request_form_spec.rb
> +  describe 'when in production and znedesk creditials are provided' do
```suggestion
  describe 'when Zendesk credentials are provided' do
```
Typo, and removed 'in production' as there's no mention of production in the test code

2021-01-06 10:59 UTC, aldavidson approved these changes

2021-01-06 11:13 UTC, merged