Update_4G-router_guidance_reset_info
DFE-Digital/get-help-with-tech pull request #1711
Opened 2021-05-18 12:56 UTC by amylaurence1

### Context
Updated information on resetting routers after 31 July 2021. 

### Changes proposed in this pull request

### Guidance to review

2021-05-19 13:44 UTC, Lloyd-K requested changes
I've suggested a couple of small changes.

2021-05-19 13:44 UTC, Lloyd-K commented on app/views/devices_guidance/4g_user_guidance.md
> +- SIM cards will work until the 31 July 2021
Suggest removing 'the'

2021-05-19 13:44 UTC, Lloyd-K commented on app/views/devices_guidance/4g_user_guidance.md
> +For technical support, children and families should contact the trust, local authority or school which sent them the router. They can help with setting up routers or raising an issue if there is a pr
there's

2021-05-19 13:44 UTC, Lloyd-K commented on app/views/devices_guidance/4g_user_guidance.md
> +In conversations with parents, carers, and children you should emphasise the importance of a safe online environment and offer support and advice on how to do this. It is also important that children
how to create this.

It's 

... clear on how to report any concerns they may have about online safety.

2021-05-20 09:04 UTC, markhallen approved these changes

2021-05-20 09:16 UTC, markhallen approved these changes

2021-05-20 09:18 UTC, merged