Makes the journey for users who have a router allocation and want to …
DFE-Digital/get-help-with-tech pull request #1766
Opened 2021-06-04 12:31 UTC by ralph-hawkins

### Context

From ticket (Review 4G router ordering journey for users (particularly ISS and SC) -are they blocked?)[https://trello.com/c/AZvS4Eku/2046-review-4g-router-ordering-journey-for-users-particularly-iss-and-sc-are-they-blocked]:

Anya reported that an LA user could not find how to order the 4G routers allocated to her. We had a call to discuss the journey and agreed that it needs a review.

### Changes proposed in this pull request

- reword 'Get laptops' pages to 'Get devices'
- show users links to these pages allow them to order routers (when they have been allocated routers)
- add a link to order routers from the 'Request internet access' page
- give guidance on how to add routers to your order in techsource

We're also updating emails sent to users when their router request is approved to give guidance on how to order and the imminent end of the data we provide for those routers. 

I've also made the router password conditional on the user’s organisation having been allocated some routers.

#### School only changes:

![localhost_3000_schools_135086](https://user-images.githubusercontent.com/8417288/120801220-ce01d880-c538-11eb-8765-bdebcc46d819.png)

#### RB only changes:

![localhost_3000_responsible-body (4)](https://user-images.githubusercontent.com/8417288/120801273-df4ae500-c538-11eb-9434-33a0d621f770.png)

#### RB and school changes:

![localhost_3000_schools_135086_internet](https://user-images.githubusercontent.com/8417288/120801362-f984c300-c538-11eb-8375-a3012b7e597b.png)

![localhost_3000_schools_135086_order-devices](https://user-images.githubusercontent.com/8417288/120801369-fc7fb380-c538-11eb-88ff-43567b8c3953.png)

### Guidance to review

Your organisation needs to have a router allocation to see the changes.

2021-06-04 12:45 UTC, Lloyd-K requested changes

2021-06-04 12:45 UTC, Lloyd-K commented on app/views/shared/_start_ordering_on_techsource.html.erb
> +      Click on the magnifying glass icon in the top right corner of the screen
Please add full stops after each numbered bullet.

2021-06-04 12:48 UTC, ralph-hawkins commented on app/views/shared/_start_ordering_on_techsource.html.erb
> +      Click on the magnifying glass icon in the top right corner of the screen
Done :-)

2021-06-07 14:46 UTC, Lloyd-K approved these changes

2021-06-07 15:34 UTC, merged