Update how_to_order.html.erb
DFE-Digital/get-help-with-tech pull request #589
Opened 2020-10-02 13:32 UTC by dannychadburndfe

### Context

### Changes proposed in this pull request

### Guidance to review

2020-10-02 13:33 UTC, dannychadburndfe commented
Updated guidance to reflect new policy and processes

2020-10-05 08:14 UTC, gemmaemoore approved these changes

2020-10-05 08:46 UTC, gemmaemoore approved these changes

2020-10-05 09:34 UTC, benilovj requested changes
![image](https://user-images.githubusercontent.com/23801/95063456-412b2480-06f6-11eb-9d95-5f335b1db06e.png)

we have two number 5's on the "how to order" page – just gonna fix that first

2020-10-05 09:42 UTC, benilovj approved these changes

2020-10-05 09:42 UTC, merged